function(executable NAME SOURCES INCLUDES LIBS)
    add_executable(${NAME} ${SOURCES})
    target_include_directories(${NAME} PRIVATE "${INCLUDES}")
    target_link_libraries(${NAME} PRIVATE "${LIBS}")
endfunction()